(1-4)ダブルサブミット対策
koki0318/ex-emp-management-bugfix pull request #2
Opened 2023-02-17 07:45 UTC by koki0318

登録フォームのメソッドにリダイレクト処理を行い、ダブルサブミット対策を行いました。
よろしくお願いいたします。
slackでいただいたコードもこのブランチで処理してしまいました。
以後気をつけて参ります。
よろしくお願いいたします。

2023-02-17 08:49 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2023-02-17 08:49 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +		return "redirect:administrator/login";
この書き方で動きますか？

私の認識違いの場合は口頭かSlackにてお知らせください。

2023-02-17 08:49 UTC, igamasayuki commented on src/main/java/com/example/controller/AdministratorController.java
> +		return "redirect:administrator/login";
動かない場合は修正してください。

2023-02-17 08:50 UTC, koki0318 commented on src/main/java/com/example/controller/AdministratorController.java
> +		return "redirect:administrator/login";
かしこまりました。
確認いたします。

2023-02-20 04:34 UTC, igamasayuki approved these changes
問題ありませんので承認いたします。

2023-02-20 04:34 UTC, merged